name: Build, Run, and Test .NET Project

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-run-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'  

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build

      - name: Run project
        run: dotnet run --project TestRunnerDemo.csproj & # the '&' allows it to run in background

      - name: Wait for API to start
        run: sleep 10  

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  

      - name: Install Newman
        run: npm install -g newman

      - name: Run API tests
        run: newman run ApiTest/NewmanIntoGithubActions.postman_collection.json -e ApiTest/IntegrationEnvironment.postman_environment.json -d ApiTest/data.json 
